export const Data = [
  {
    title: 'React-Resturant',
    description: "I'm a beginner to React, however I've been using it for quite some time now. I had a lot of fun doing this project and learnt a lot about using React.",
      image: require('./images/1.png'),
      tags: ['React', 'Css',"Tailwind"],
    source: 'https://billal2022.github.io/ch1-React-Resturant/',
    visit: 'https://github.com/billal2022/ch1-React-Resturant.git',
    id: 0,
  },
  {
    title: 'Insure landing page',
    description:" Testing my layout skills with this HTML & CSS only landing page. This challenge is perfect if am starting to get confident in laying out web pages.",
    image: require('./images/2.png'),
    tags: ['Html','Scss','Css', 'Bootstap'],
    source: 'https://billal2022.github.io/ch27-FEM-Insure-landing-page/',
    visit: 'https://github.com/billal2022/ch27-FEM-Insure-landing-page.git',
    id: 1,
  },
  {
    title: 'Project tracking intro component',
    description: "Some interesting layout and code challenges are baked into this design. Perfect if i am a beginner who is starting to get a bit more confident with my layouts.",
      image: require('./images/3.png'),
      tags: ['Html','Scss','Css', 'Bootstap'],
    source: 'https://billal2022.github.io/ch-26-FEM-project-tracking-intro-component-master/',
    visit: 'https://github.com/billal2022/ch-26-FEM-project-tracking-intro-component-master.git',
    id: 2,
  },
  {
    title: 'Social media dashboard with theme switcher',
    description: "In this project, I  built out an interactive pricing component complete with custom range input slider and pricing toggle. A perfect way to test my JS skills!",
    image: require('./images/4.png'),
    tags: ['Html','Scss','Css', 'Bootstap'],
    source: 'https://billal2022.github.io/ch24-FEM-Interactive-pricing-component/',
    visit: 'https://github.com/billal2022/ch24-FEM-Interactive-pricing-component.git',
    id: 3,
  },
]